name: test/build/deploy

on:
  push:
    branches:
      - front

jobs:
  CICD:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Jesting
      run: yarn ci
    - name: Codecov(erage)
      uses: codecov/codecov-action@v1
      if: always()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Cypress
      uses: cypress-io/github-action@v2
      with:
        install: false
        headless: true
        start: yarn start
        wait-on: 'http://localhost:3000/'
        wait-on-timeout: 120
        browser: chrome
        record: true
      env:
        CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - name: Build
      run: yarn build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: build